<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	

</style>

	<link rel="stylesheet" href="//code.jquery.com/ui/1.11.3/themes/smoothness/jquery-ui.css">
	<script src="//code.jquery.com/jquery-1.10.2.js"></script>
	<script src="//code.jquery.com/ui/1.11.3/jquery-ui.js"></script>
	<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false&v=3&libraries=geometry"></script>

	<script>

	
		<?php include 'common.php'; ?>

		<!-- On server-side generates the "var webURLString = '...'" -->		
		<?php echo "var webURLString = '" . getWebURLString() ."';"; ?>	
		
		var map;
		var infoWindows = [];  				//For keep track of opened Info Windows
		var excursionArray = [];
		
		var actualExcursionId = null;
		var actualExcursionName = null;
			
		/**
		* It Initializes the MAP
		* Size, position, markers
		*/
		function initialize() {
			var mapProp = {
			    center:new google.maps.LatLng(47.214688, 19.606562),
			    zoom:7,
			    mapTypeId:google.maps.MapTypeId.ROADMAP,
			    panControl: false,
			    zoomControl: false,
			    mapTypeControl: true,
			    scaleControl: false,
			    streetViewControl: true,			    			  			    
			};
			map = new google.maps.Map(document.getElementById("map_canvas"),mapProp);
		
			$.ajax({
				type: "GET",
				url: webURLString + "get_excursion_list.php",
				contentType: "text/html",
				dataType: "xml",
				async:true,
				success: getExcursionListSuccess,
				error: getError
			});
		}

		/**
		*
		* Get Excursions and show them in table
		* It fills out the list (only once)
		*/		
		function getExcursionListSuccess( data, status, req ){

			if( status =="success"){	

				//<excursion id= "" name="" dateStart="" dateEnd="">
				$(data).find("excursion").each(function(){

					//id
					var excursionId = $(this).attr("id");
					var excursionName = $(this).attr("name");
					var excursionDateStart = $(this).attr("dateStart");

					$('#excursionList').append("<tr><td><div id='" + excursionId + "'>" + excursionName + "</div></td><td>" + excursionDateStart.substring(0, 4) + "</td></tr>");

					//
					//Kivalasztottam valamelyik kirandulast
					//
					$( "#" + excursionId ).click(function() {

						//Close all opened infowindow
						closeAllOpenedInfowindow();
						
						actualExcursionId = excursionId;
						actualExcursionName = excursionName;

						//Check if the excursion appeared
						excursionObject = excursionArray[ excursionId ];						

						//The excursion does not appear yet
						if( excursionObject == null ){

							//Make it appear if it is not yet
							$.ajax({
								type: "GET",
								url: webURLString + "get_details_by_excursion_id.php",
								data: { 'excursionid': excursionId },
								contentType: "text/html",
								dataType: "xml",
								async:true,
								success: getDetailsByExcursionIdSuccess,
								error: getError
							});

						//The excurion must be delete
						}else{

							for (var i in excursionObject) {
								excursionObject[i].setMap(null);
							}
							excursionArray[ excursionId ] = null;
														
						}
							
					});					
				});
			}
		}

		/**
		*
		* It shows data of the selected excursion
		*
		*/
		function getDetailsByExcursionIdSuccess( data, status, req ){
			
			if( status =="success"){

var shownGraphics = [];
				
				//<tour id="" type="">
				$(data).find("tour").each(function(){
					var tourId = $(this).attr("id");
					var tourType = $(this).attr("type");
					var tourDay = $(this).attr("day");

					//The route path is empty
					var routePathArray = new Array();
					var preLatLong = null;
					var tourLength = 0;					
				
					//<route lat="" lng="" time="">
					$(this).find("route").each(function(){
						routeLat = parseFloat( $(this).attr("lat") );
						routeLng = parseFloat( $(this).attr("lng") );
						routeTime = $(this).find("time").text();
						routeLatLong = new google.maps.LatLng(routeLat, routeLng);
						if( preLatLong != null ){
							routeDistance = google.maps.geometry.spherical.computeDistanceBetween (preLatLong, routeLatLong);
							tourLength += routeDistance;
						}
						preLatLong = routeLatLong;
						
						//Add new section to the route path
						routePathArray[routePathArray.length] = new google.maps.LatLng( routeLat, routeLng );
						 
					});

					//Tour path
					var routePath = new google.maps.Polyline({
						path: routePathArray,
						strokeColor: "#0000FF",
						strokeOpacity: 0.5,
						strokeWeidht: 5
					});
					routePath.setMap(map);

shownGraphics.push(routePath);					
					
					//Tour infowindow				
					var infoWindow = new google.maps.InfoWindow({
						content:
							"<center><b><?php echo getTranslation('label.infowindow.tour.title')?></b></center>"+
							"<br><?php echo getTranslation('label.infowindow.tour.excursion')?> : " + actualExcursionName +
							"<br><?php echo getTranslation('label.infowindow.tour.day') ?> : " + tourDay +							
							"<br><?php echo getTranslation('label.infowindow.tour.type')?> : " + <?php echo getTranslation( tourType )?> + 
							"<br><?php echo getTranslation('label.infowindow.tour.length')?>: " + tourLength.toFixed(2) + " m"
					});

					infoWindows.push( infoWindow );

					//In case of Click on the path, an Info Window appears
					google.maps.event.addListener(routePath, 'click', function(event) {
						mLat = event.latLng.lat();
	                    mLng = event.latLng.lng();

	                  	//Close all opened Info Window
	                  	closeAllOpenedInfowindow();

						infoWindow.setPosition(event.latLng);
						infoWindow.open(map);
					});
					
				});

				//<accomodation accomodation_id="" excursion_name="" accomodation_name="" accomodation_type="" accomodation_address="" accomodation_lat="" accomodation_lng="">
				$(data).find("accomodation").each(function(){
					accomodationId = $(this).attr("accomodation_id");
					accomodationName = $(this).attr("accomodation_name");
					accomodationType = $(this).attr("accomodation_type");
					accomodationAddress = $(this).attr("accomodation_address");
					accomodationLat = $(this).attr("accomodation_lat");
					accomodationLng = $(this).attr("accomodation_lng");

					var marker = new google.maps.Marker({
						position: new google.maps.LatLng( accomodationLat, accomodationLng ),
						map: map,
					});
					
shownGraphics.push(marker);

					var days = "";
					$(this).find("day").each(function(){	
						if( days != "" ){
							days += ", ";
						}
						days += $(this).text();						
					});

					//Accomodation infowindow
					var infoWindow = new google.maps.InfoWindow({
						content: 
							"<center><b><?php echo getTranslation('label.infowindow.accomodation.title')?></b></center>"+
							"<br><?php echo getTranslation('label.infowindow.accomodatioin.excursionname')?> : " + actualExcursionName +
							"<br><?php echo getTranslation('label.infowindow.accomodation.name')?>: " + accomodationName + 
							"<br><?php echo getTranslation('label.infowindow.accomodation.address')?>: " + accomodationAddress + 
							"<br><?php echo getTranslation('label.infowindow.accomodation.type')?>: " + accomodationType + 
							"<br><?php echo getTranslation('label.infowindow.accomodation.reserved')?>: " + days						
					});

					infoWindows.push( infoWindow );

					//In case of Click on the path, an Info Window appears
					google.maps.event.addListener(marker, 'click', function(event) {
						mLat = event.latLng.lat();
	                    mLng = event.latLng.lng();
	                    
						//Close all opened Info Window
						closeAllOpenedInfowindow();

						infoWindow.setPosition(event.latLng);
						infoWindow.open(map);
					});

					//Arrange it to center
					//var center = new google.maps.LatLng(accomodationLat, accomodationLng);
				    //map.panTo(center);				
					
				});	

excursionArray[ actualExcursionId ] = shownGraphics;				
							
			}
		}

		function getError( data, status, req ){
			alert( 'Hiba az ajax híváskor: \n' + data.responseText ); // + '\nstatus: ' + status + '\n' + 'req: ' + req.responseText);
		}

      	/**
		* Close all opened Info Window
		*/	                  	
      	function closeAllOpenedInfowindow(){        
			for (var i=0;i<infoWindows.length;i++) {
				infoWindows[i].close();
			}
      	}
      	
		$(function() {

			$("#resize_canvas").resizable({
	      		"resize" : function(event,ui) {
	            	google.maps.event.trigger(map,'resize');
	      		}
			});
		});
		
		google.maps.event.addDomListener(window, 'load', initialize);

	</script>
</head>

<body>

	<table border="1">
		<tr>
			
			<td>
				<div id="resize_canvas" class="ui-widget-content" style="padding:0px;border:0;width:700px;height:450px;" >
					<div id="map_canvas" class="ui-widget-content" style="width:100%;height:100%;" ></div>				
				</div>
			</td>

			<td valign="top">
				<table border="2" id="excursionList">
					<tr>
						<th><?php echo getTranslation("label.table.excursion")?></th>
						<th><?php echo getTranslation("label.table.year")?></th>
					</tr>
				</table>
			</td>
		</tr>
	</table>
</body>

</html> 




