<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	
</style>

 	<script src="js/common.js"></script> 
	<link rel="stylesheet" type="text/css" href="css/tris.css">
	<link rel="stylesheet" href="//code.jquery.com/ui/1.11.3/themes/smoothness/jquery-ui.css">
	<script src="//code.jquery.com/jquery-1.10.2.js"></script>
	<script src="//code.jquery.com/ui/1.11.3/jquery-ui.js"></script>
	<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false&v=3&libraries=geometry"></script>
 	
	<script>

		<!-- Common functions -->
		<?php include 'common.php'; ?>

		<!-- On server-side generates the "var webURLString = '...'" -->		
		<?php echo "var webURLString = '" . getWebURLString() ."';"; ?>
	
		var map;
		var infoWindows = [];  				//For keep track of opened Info Windows
		var excursionArray = {};
		
		var actualExcursionId = null;
		var actualExcursionName = null;
		var actualExcursionColor = "#FF0000";
		var actualExcurionsImage = null;
		
		/**
		*
		* Initializes the MAP
		* Size, position, markers
		*
		*/
		function initialize() {

			//
			// Language section
			//	
			var language = "<?php echo getActualLanguage(); ?>";
			imgName = webURLString+"icons/language_" + language + ".png";	

			$('#language_menu').append($('<option/>', { 
				value: "hu",
				text : "Magyar" 
		    }));
			$('#language_menu').append($('<option/>', { 
				value: "en",
				text : "English" 
		    }));
		    
			$('#language_menu').val( language ).change();

			$('#language_menu').change( function(){			
				setCookie( "<?php echo $cookieLanguage ?>", $(this).val());
				location.reload();
			});

			$("#resize_canvas").resizable({
	      		"resize" : function(event,ui) {
	            	google.maps.event.trigger(map,'resize');
	      		}
			});
			
			var mapProp = {
			    center:new google.maps.LatLng(47.214688, 19.606562),
			    zoom:7,
			    mapTypeId:google.maps.MapTypeId.ROADMAP,
			    panControl: false,
			    zoomControl: false,
			    mapTypeControl: true,
			    scaleControl: false,
			    streetViewControl: true,			    			  			    
			};
			map = new google.maps.Map(document.getElementById("map_canvas"),mapProp);
		
			$.ajax({
				type: "GET",
				url: webURLString + "get_excursion_list.php",
				contentType: "text/html",
				dataType: "json",
				async:true,
				success: getExcursionListSuccess,
				error: getError
			});
		}

		/**
		*
		* Get Excursions and show them in table
		* It fills out the list (only once)
		*/		
		function getExcursionListSuccess( data, status, req ){

			if( status =="success"){	

				//Megkeresi az "excurions" array-t es vegig megy minden elemen 
				$.each( data.excursions, function( index, element ){

					var excursionId = element.id;
					var excursionName = element.name;
					var excursionDateStart = element.dateStart;
					var excursionColor = element.color;

					//$('#excursion_list').append("<tr><td><div id='" + excursionId + "' shown='false'>" + excursionName + "</div></td><td>" + excursionDateStart + "</td></tr>");
					$('#excursion_list table').append("<tr id='" + excursionId + "' shown='false'><td>" + excursionName + "</td><td>" + excursionDateStart + "</td></tr>");					

					//
					//Kivalasztottam valamelyik kirandulast
					//
					$( "#" + excursionId ).click(function() {

						//Close all opened infowindow
						closeAllOpenedInfowindow();
						
						actualExcursionId = excursionId;
						actualExcursionName = excursionName;
						actualExcursionColor = excursionColor;

						//Check if the excursion appeared
						excursionObject = excursionArray[ excursionId ];						

						//The excursion does not appear yet
						if( excursionObject == null ){

							//Make it appear if it is not yet
							$.ajax({
								type: "GET",
								url: webURLString + "get_details_by_excursion_id.php",
								data: { 'excursionid': excursionId },
								contentType: "text/html",
								dataType: "xml",
								async:true,
								selectedElement: this,
								success: getDetailsByExcursionIdSuccess,
								error: getError
							});

						//The excurion must be deleted
						}else{
							
							for (var i in excursionObject) {
								excursionObject[i].setMap(null);
							}

/*							$.each(excursionArray, function(key, value){
							    alert(key + ": " + value +"/n");
							});
*/							
							
							delete excursionArray[excursionId];						
							//excursionArray.splice( $.inArray(excursionArray[excursionId], excursionArray), 1 );
							//excursionArray[ excursionId ] = null;

/*$.each(excursionArray, function(key, value){
    alert(key + ": " + value +"/n");
});*/							
							
							//Set the CHECKED attribute to FALSE							
							$(this).attr("shown", "false");							
							setExcursionDetailsIfNecessary();					
						}
					});		
				});
			}
		}
    		
		/**
		*
		* It shows data of the selected excursion
		*
		*/
		function getDetailsByExcursionIdSuccess( data, status, req ){
		
			if( status =="success"){

				//Graphical elements (routePath, marker) administration
				var shownGraphics = [];
				
				//<tour id="" type="">
				$(data).find("tour").each(function(){
					var tourId = $(this).attr("id");
					var tourType = $(this).attr("type");
					var tourDay = $(this).attr("day");

					//The route path is empty
					var routePathArray = new Array();
					var preLatLong = null;
					var tourLength = 0;					
				
					//<route lat="" lng="" time="">
					$(this).find("route").each(function(){
						routeLat = parseFloat( $(this).attr("lat") );
						routeLng = parseFloat( $(this).attr("lng") );
						routeTime = $(this).find("time").text();
						routeLatLong = new google.maps.LatLng(routeLat, routeLng);
						if( preLatLong != null ){
							routeDistance = google.maps.geometry.spherical.computeDistanceBetween (preLatLong, routeLatLong);
							tourLength += routeDistance;
						}
						preLatLong = routeLatLong;
						
						//Add new section to the route path
						routePathArray[routePathArray.length] = new google.maps.LatLng( routeLat, routeLng );
						 
					});

					//Tour path
					var routePath = new google.maps.Polyline({
						path: routePathArray,
						strokeColor: "#0000FF",
						strokeOpacity: 0.5,
						strokeWeidht: 5
					});
					routePath.setMap(map);

					//Keep track of routePath
					shownGraphics.push(routePath);					
				
					//Tour infowindow				
					var infoWindow = new google.maps.InfoWindow({
						content:
							"<table class='info-window' border='0'>"+
								"<tr colspan='1'>"+
									"<th>" +
										"<center><b><?php echo getTranslation('label.infowindow.tour.title')?></b></center>"+
									"</th>" +
								"</tr>" +
								"<tr>" +
									"<td>" +
										"<table border='0'>"+
											"<tr>"+
												"<td><?php echo getTranslation('label.infowindow.tour.excursion')?> : </td><td>" + actualExcursionName + "</td>"+
											"</tr>"+
											"<tr>"+
												"<td><?php echo getTranslation('label.infowindow.tour.day') ?> : </td><td>" + tourDay +	"</td>"+
											"</tr>"+
											"<tr>"+
												"<td><?php echo getTranslation('label.infowindow.tour.type')?> : </td><td>" + tourType + "</td>"+	
											"</tr>"+
											"<tr>"+
												"<td><?php echo getTranslation('label.infowindow.tour.length')?>: </td><td>" + tourLength.toFixed(2) + " m" + "</td>"+	
											"</tr>"+
										"</table>"+
									"</td>" +									
								"</tr>" +							
							"</table>"
							
					});

					infoWindows.push( infoWindow );

					//In case of Click on the path, an Info Window appears
					google.maps.event.addListener(routePath, 'click', function(event) {
						mLat = event.latLng.lat();
	                    mLng = event.latLng.lng();

	                  	//Close all opened Info Window
	                  	closeAllOpenedInfowindow();

						infoWindow.setPosition(event.latLng);
						infoWindow.open(map);
					});
					
				});

				//<accomodation accomodation_id="" excursion_name="" accomodation_name="" accomodation_type="" accomodation_address="" accomodation_lat="" accomodation_lng="">
				$(data).find("accomodation").each(function(){
					accomodationId = $(this).attr("accomodation_id");
					accomodationName = $(this).attr("accomodation_name");
					accomodationType = $(this).attr("accomodation_type");
					accomodationAddress = $(this).attr("accomodation_address");
					accomodationLat = $(this).attr("accomodation_lat");
					accomodationLng = $(this).attr("accomodation_lng");
					accomodationIcon = $(this).attr("accomodation_icon");

					var marker = new google.maps.Marker({
						position: new google.maps.LatLng( accomodationLat, accomodationLng ),
						map: map,
						icon: getPinImage(actualExcursionColor),
			            shadow: getPinShadow()
					});

					//Kepp track of marker
					shownGraphics.push(marker);

					var days = "";
					$(this).find("day").each(function(){	
						if( days != "" ){
							days += ", <br>";
						}
						days += $(this).text();						
					});

					//Accomodation infowindow
					var infoWindow = new google.maps.InfoWindow({
						content: 
							"<table class='info-window' border='0'>"+
								"<tr colspan='2'>"+
									"<th>" +
										"<center><b><?php echo getTranslation('label.infowindow.accomodation.title')?></b></center>"+
									"</th>" +
								"</tr>" +
								"<tr>" +
									"<td>" +
										"<table border='0'>"+
											"<tr>"+
												"<td valign='top'><?php echo getTranslation('label.infowindow.accomodatioin.excursionname')?> : </td><td>" + actualExcursionName + "</td>"+		
											"</tr>"+
											"<tr>"+
												"<td valign='top'><?php echo getTranslation('label.infowindow.accomodation.name')?>: </td><td>" + accomodationName + "</td>" +
											"</tr>"+
											"<tr>"+
												"<td valign='top'><?php echo getTranslation('label.infowindow.accomodation.address')?>: </td><td>" + accomodationAddress + "</td>" +
											"</tr>"+
											"<tr>"+
												"<td><?php echo getTranslation('label.infowindow.accomodation.type')?>: </td><td>" + accomodationType + "</td>" +
											"</tr>"+
											"<tr>"+
												"<td valign='top'><?php echo getTranslation('label.infowindow.accomodation.reserved')?>: </td><td>" + days + "</td>" +
											"</tr>"+
										"</table>"+			
									"</td>" +
									"<td valign='top'>" +
										"<img src=" + accomodationIcon + ">"+
									"</td>" +
								"</tr>" +							
							"</table>"
																			
					});

					infoWindows.push( infoWindow );

					//In case of Click on the path, an Info Window appears
					google.maps.event.addListener(marker, 'click', function(event) {
						mLat = event.latLng.lat();
	                    mLng = event.latLng.lng();
	                    
						//Close all opened Info Window
						closeAllOpenedInfowindow();

						infoWindow.setPosition(event.latLng);
						infoWindow.open(map);
					});

					//Arrange it to center
					//var center = new google.maps.LatLng(accomodationLat, accomodationLng);
				    //map.panTo(center);				
					
				});	

				//graphical elements of the actual excursion goes into an array
				excursionArray[ actualExcursionId ] = shownGraphics;
				
				//Set the CHECKED attribute to TRUE							
				$(this.selectedElement).attr("shown", "true");
				setExcursionDetailsIfNecessary();
											
			}
		}

		function getError( data, status, req ){
			alert( 'Hiba az ajax híváskor: \n' + data.responseText ); // + '\nstatus: ' + status + '\n' + 'req: ' + req.responseText);
		}

		function setExcursionDetailsIfNecessary(){

			var excursionId = null;
			
			//If only One Excursion selected
			if( Object.keys(excursionArray).length == 1 ){

				//Get the excursion ID
				$.each(excursionArray, function(key, value){
					excursionId = key;
					break;				    
				});
				
				$('#excursion_details').append(
					"<table border='1'>" +
					"</table>"
			    );
				$('#excursion_details table').append("<tr colspan='2'><td>" + "hello" + "</td></tr>");

				$('#excursion_details table').append("<tr><td>" + "hello" + "</td><td>" + "hello" + "</td></tr>");		
			    
				
			//0 or more than 1 Excursions selected
			}else{

				//Disappears all details
				$("#excursion_details table").remove(); 
			}
		}
			
      	/**
		* Close all opened Info Window
		*/	                  	
      	function closeAllOpenedInfowindow(){        
			for (var i=0;i<infoWindows.length;i++) {
				infoWindows[i].close();
			}
      	}

		function getPinImage( color ){
			var pinImage = new google.maps.MarkerImage("http://chart.apis.google.com/chart?chst=d_map_pin_letter&chld=%E2%80%A2|" + color,
			    new google.maps.Size(21, 34),
			    new google.maps.Point(0,0),
		    	new google.maps.Point(10, 34));
	    	return pinImage;
		}
		
		function getPinShadow(){
			var pinShadow = new google.maps.MarkerImage("http://chart.apis.google.com/chart?chst=d_map_pin_shadow",
		    	new google.maps.Size(40, 37),
		    	new google.maps.Point(0, 0),
		    	new google.maps.Point(12, 35));
	    	return pinShadow;
		}
		
		//If the DOM loaded then starts the initialize
		google.maps.event.addDomListener(window, 'load', initialize);

	</script>
</head>

<body>

	<!-- Upper menu line -->
	<div id="upper_menuline">
		<div id="upper_menu">
			<table border="0">
				<tr >
					<td>
						Login
					</td>
					<td>
						<!-- Language selector -->
						<select id="language_menu"></select>				
					
					</td>
				</tr>				
			</table>
		</div>
	</div>
	
	<div id="work_place">
	
		<div id="resize_canvas" class="ui-widget-content" style="padding:0px;border:0;width:100%;height:450px;" >
			<div id="map_canvas" class="ui-widget-content" style="width:100%;height:100%;" ></div>				
		</div>

		<div id="excursion_list">
			<table border="0"  cellspacing="0">
				<tr>
					<th><?php echo getTranslation("label.table.excursion")?></th>
					<th><?php echo getTranslation("label.table.date")?></th>
				</tr>
			</table>					
		</div>
		
		<div id="excursion_details"></div>
	
	
	</div>	
<!-- 		
	<table border="0">
		<tr>			
			<td>
				<div id="resize_canvas" class="ui-widget-content" style="padding:0px;border:0;width:700px;height:450px;" >
					<div id="map_canvas" class="ui-widget-content" style="width:100%;height:100%;" ></div>				
				</div>
			</td>

			<td valign="top">
				<table border="0" id="excursion_list" cellspacing="0">
					<tr>
						<th><?php echo getTranslation("label.table.excursion")?></th>
						<th><?php echo getTranslation("label.table.date")?></th>
					</tr>
				</table>
			</td>
		</tr>
	</table>
 -->				
				

	
</body>

</html> 




